spring:
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    h2:
      console:
          enabled: true
          path: /h2


server:
    port: 7800


eureka:
    client:
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
  #indicates the frequency the client sends heartbeat to server to indicate that it is alive.
    instance:
        lease-renewal-interval-in-seconds: 30
